//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TeachPlan
{
    public partial class Content
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Active> Huodong
        {
            get
            {
                if (_huodong == null)
                {
                    var newCollection = new FixupCollection<Active>();
                    newCollection.CollectionChanged += FixupHuodong;
                    _huodong = newCollection;
                }
                return _huodong;
            }
            set
            {
                if (!ReferenceEquals(_huodong, value))
                {
                    var previousValue = _huodong as FixupCollection<Active>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupHuodong;
                    }
                    _huodong = value;
                    var newValue = value as FixupCollection<Active>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupHuodong;
                    }
                }
            }
        }
        private ICollection<Active> _huodong;

        #endregion
        #region Association Fixup
    
        private void FixupHuodong(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Active item in e.NewItems)
                {
                    if (!item.Content.Contains(this))
                    {
                        item.Content.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Active item in e.OldItems)
                {
                    if (item.Content.Contains(this))
                    {
                        item.Content.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
