//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TeachPlan
{
    public partial class Phase
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Active> Active
        {
            get
            {
                if (_active == null)
                {
                    var newCollection = new FixupCollection<Active>();
                    newCollection.CollectionChanged += FixupActive;
                    _active = newCollection;
                }
                return _active;
            }
            set
            {
                if (!ReferenceEquals(_active, value))
                {
                    var previousValue = _active as FixupCollection<Active>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupActive;
                    }
                    _active = value;
                    var newValue = value as FixupCollection<Active>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupActive;
                    }
                }
            }
        }
        private ICollection<Active> _active;

        #endregion
        #region Association Fixup
    
        private void FixupActive(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Active item in e.NewItems)
                {
                    if (!item.Phase.Contains(this))
                    {
                        item.Phase.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Active item in e.OldItems)
                {
                    if (item.Phase.Contains(this))
                    {
                        item.Phase.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
