//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TeachPlan
{
    public partial class Target
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int Type
        {
            get;
            set;
        }
    
        public virtual string Baseic
        {
            get;
            set;
        }
    
        public virtual string Advance
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Plan Plan
        {
            get { return _plan; }
            set
            {
                if (!ReferenceEquals(_plan, value))
                {
                    var previousValue = _plan;
                    _plan = value;
                    FixupPlan(previousValue);
                }
            }
        }
        private Plan _plan;

        #endregion
        #region Association Fixup
    
        private void FixupPlan(Plan previousValue)
        {
            if (previousValue != null && previousValue.Target.Contains(this))
            {
                previousValue.Target.Remove(this);
            }
    
            if (Plan != null)
            {
                if (!Plan.Target.Contains(this))
                {
                    Plan.Target.Add(this);
                }
            }
        }

        #endregion
    }
}
