//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace TeachPlan
{
    public partial class JiaoxueJihuaContainer : ObjectContext
    {
        public const string ConnectionString = "name=JiaoxueJihuaContainer";
        public const string ContainerName = "JiaoxueJihuaContainer";
    
        #region Constructors
    
        public JiaoxueJihuaContainer()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public JiaoxueJihuaContainer(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public JiaoxueJihuaContainer(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Plan> PlanSet
        {
            get { return _planSet  ?? (_planSet = CreateObjectSet<Plan>("PlanSet")); }
        }
        private ObjectSet<Plan> _planSet;
    
        public ObjectSet<Think> ThinkSet
        {
            get { return _thinkSet  ?? (_thinkSet = CreateObjectSet<Think>("ThinkSet")); }
        }
        private ObjectSet<Think> _thinkSet;
    
        public ObjectSet<Judge> JudgeSet
        {
            get { return _judgeSet  ?? (_judgeSet = CreateObjectSet<Judge>("JudgeSet")); }
        }
        private ObjectSet<Judge> _judgeSet;
    
        public ObjectSet<Ready> ReadySet
        {
            get { return _readySet  ?? (_readySet = CreateObjectSet<Ready>("ReadySet")); }
        }
        private ObjectSet<Ready> _readySet;
    
        public ObjectSet<Target> TargetSet
        {
            get { return _targetSet  ?? (_targetSet = CreateObjectSet<Target>("TargetSet")); }
        }
        private ObjectSet<Target> _targetSet;
    
        public ObjectSet<Active> ActiveSet
        {
            get { return _activeSet  ?? (_activeSet = CreateObjectSet<Active>("ActiveSet")); }
        }
        private ObjectSet<Active> _activeSet;
    
        public ObjectSet<Character> CharacterSet
        {
            get { return _characterSet  ?? (_characterSet = CreateObjectSet<Character>("CharacterSet")); }
        }
        private ObjectSet<Character> _characterSet;
    
        public ObjectSet<Point> PointSet
        {
            get { return _pointSet  ?? (_pointSet = CreateObjectSet<Point>("PointSet")); }
        }
        private ObjectSet<Point> _pointSet;
    
        public ObjectSet<Method> MethodSet
        {
            get { return _methodSet  ?? (_methodSet = CreateObjectSet<Method>("MethodSet")); }
        }
        private ObjectSet<Method> _methodSet;
    
        public ObjectSet<Step> StepSet
        {
            get { return _stepSet  ?? (_stepSet = CreateObjectSet<Step>("StepSet")); }
        }
        private ObjectSet<Step> _stepSet;
    
        public ObjectSet<Subject> SubjectSet
        {
            get { return _subjectSet  ?? (_subjectSet = CreateObjectSet<Subject>("SubjectSet")); }
        }
        private ObjectSet<Subject> _subjectSet;
    
        public ObjectSet<Content> ContentSet
        {
            get { return _contentSet  ?? (_contentSet = CreateObjectSet<Content>("ContentSet")); }
        }
        private ObjectSet<Content> _contentSet;
    
        public ObjectSet<Phase> PhaseSet
        {
            get { return _phaseSet  ?? (_phaseSet = CreateObjectSet<Phase>("PhaseSet")); }
        }
        private ObjectSet<Phase> _phaseSet;
    
        public ObjectSet<UserInfo> UserInfoSet
        {
            get { return _userInfoSet  ?? (_userInfoSet = CreateObjectSet<UserInfo>("UserInfoSet")); }
        }
        private ObjectSet<UserInfo> _userInfoSet;
    
        public ObjectSet<Grade> GradeSet
        {
            get { return _gradeSet  ?? (_gradeSet = CreateObjectSet<Grade>("GradeSet")); }
        }
        private ObjectSet<Grade> _gradeSet;
    
        public ObjectSet<Textbook> TextbookSet
        {
            get { return _textbookSet  ?? (_textbookSet = CreateObjectSet<Textbook>("TextbookSet")); }
        }
        private ObjectSet<Textbook> _textbookSet;
    
        public ObjectSet<Form> FormSet
        {
            get { return _formSet  ?? (_formSet = CreateObjectSet<Form>("FormSet")); }
        }
        private ObjectSet<Form> _formSet;

        #endregion
    }
}
