//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TeachPlan
{
    public partial class Textbook
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Plan> Fangan
        {
            get
            {
                if (_fangan == null)
                {
                    var newCollection = new FixupCollection<Plan>();
                    newCollection.CollectionChanged += FixupFangan;
                    _fangan = newCollection;
                }
                return _fangan;
            }
            set
            {
                if (!ReferenceEquals(_fangan, value))
                {
                    var previousValue = _fangan as FixupCollection<Plan>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupFangan;
                    }
                    _fangan = value;
                    var newValue = value as FixupCollection<Plan>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupFangan;
                    }
                }
            }
        }
        private ICollection<Plan> _fangan;

        #endregion
        #region Association Fixup
    
        private void FixupFangan(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Plan item in e.NewItems)
                {
                    item.Textbook = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Plan item in e.OldItems)
                {
                    if (ReferenceEquals(item.Textbook, this))
                    {
                        item.Textbook = null;
                    }
                }
            }
        }

        #endregion
    }
}
