//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TeachPlan
{
    public partial class UserInfo
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string PWD
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Plan> Plan
        {
            get
            {
                if (_plan == null)
                {
                    var newCollection = new FixupCollection<Plan>();
                    newCollection.CollectionChanged += FixupPlan;
                    _plan = newCollection;
                }
                return _plan;
            }
            set
            {
                if (!ReferenceEquals(_plan, value))
                {
                    var previousValue = _plan as FixupCollection<Plan>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPlan;
                    }
                    _plan = value;
                    var newValue = value as FixupCollection<Plan>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPlan;
                    }
                }
            }
        }
        private ICollection<Plan> _plan;

        #endregion
        #region Association Fixup
    
        private void FixupPlan(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Plan item in e.NewItems)
                {
                    item.UserInfo = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Plan item in e.OldItems)
                {
                    if (ReferenceEquals(item.UserInfo, this))
                    {
                        item.UserInfo = null;
                    }
                }
            }
        }

        #endregion
    }
}
